In [ ]:
## SECTION 1: DATA PREPROCESSING

In [ ]:
# 1. DATA LOADING

In [1]:
'''Importing Necessary Libraries'''
import glob
import os
import pandas as pd
import geopandas as gpd

In [2]:
'''Loading Street Crime Files'''

# loading all street crime CSV files
crime_files = glob.glob("crime_data/*/*street*.csv")

crime_list = []

# Combining all monthly crime files into one dataframe

for file in crime_files:
    df = pd.read_csv(file)
    crime_list.append(df)

crime_df = pd.concat(crime_list, ignore_index=True)

In [3]:
'''Quick inspection'''
crime_df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,71559ac1da22a7f37aa9903b221cf37d0421161dd0af10...,2024-09,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Burglary,Investigation complete; no suspect identified,NaN
1,1b283393948b1eab734d27e1a61ceffe11f9ace552775e...,2024-09,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,Unable to prosecute suspect,NaN
2,81a36ac50ea09f197158277c7000c2dd4dfac74707019d...,2024-09,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Violence and sexual offences,Unable to prosecute suspect,NaN
3,0db45b92c423603a27a97bae30f5f919ce1b2d177eeb0e...,2024-09,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,Unable to prosecute suspect,NaN
4,NaN,2024-09,Sussex Police,Sussex Police,-0.224424,50.839417,On or near St Louie Close,E01031350,Adur 001B,Anti-social behaviour,NaN,NaN

In [4]:
crime_df.tail()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
1226059,6d5bfeae0cf13524351afc302d1f20156b2f7864898e89...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,Investigation complete; no suspect identified,NaN
1226060,43a231da6279502eccd41e20ccd071de349cb80e17295f...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,Further investigation is not in the public int...,NaN
1226061,50e8d9e3ad37b272a9780873ee36a0a65fe0415f7d9bb4...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,Unable to prosecute suspect,NaN
1226062,105bbaa7db4b8c9f69e266234bd1de904dfa375f21f89c...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,Action to be taken by another organisation,NaN
1226063,4480d7f25eb658fd55832b05598f8380b50c03af5a7a6d...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,Unable to prosecute suspect,NaN

In [5]:
'''Loading Outcomes Files'''

# loading all outcomes CSV files
outcome_files = glob.glob("crime_data/*/*outcomes*.csv")

outcome_list = []

# Combining all monthly outcome files into one dataframe
for file in outcome_files:
    df = pd.read_csv(file)
    outcome_list.append(df)

outcomes_df = pd.concat(outcome_list, ignore_index=True)

In [6]:
'''Quick Inspection'''
outcomes_df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
0,01a91adf801338cfc1e11c8e606803f4d9c3b6c3f83edb...,2024-09,Hampshire Constabulary,Hampshire Constabulary,-1.381194,50.918385,On or near Englefield Road,E01017172,Southampton 014B,Offender given a caution
1,94970587eda919f242136c6cc18d3c89b4ccbf8ac9b71c...,2024-09,Hampshire Constabulary,Hampshire Constabulary,-1.492105,50.917913,On or near Sunny Way,E01023074,New Forest 004A,Investigation complete; no suspect identified
2,cf4c28078a4388e2ea55deee9bff56f4592cbd0463ef1c...,2024-09,Hampshire Constabulary,Hampshire Constabulary,-1.182257,50.852568,On or near West Street,E01022723,Fareham 008C,Investigation complete; no suspect identified
3,1a390d95cc53495d5f2915d25f06c6bcafa01e488b78c4...,2024-09,Hampshire Constabulary,Hampshire Constabulary,-1.284640,50.703763,On or near Howard Close,E01017311,Isle of Wight 008B,Unable to prosecute suspect
4,c8341a90c20463c7ff0f63b06cacdf9d6bcd442d32c476...,2024-09,Hampshire Constabulary,Hampshire Constabulary,-1.088392,50.800326,On or near Shopping Area,E01017032,Portsmouth 027C,Investigation complete; no suspect identified

In [7]:
outcomes_df.tail()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
1060784,78c2f037fc34a5b08557f26d25676395031174323ab520...,2024-10,Sussex Police,Sussex Police,-0.142439,50.824147,On or near Windsor Street,E01016969,Brighton and Hove 027E,Suspect charged
1060785,98bbbfb0e9ee6225dd40b2cc367e346d3f4fc4ecfb9b0c...,2024-10,Sussex Police,Sussex Police,-0.142449,50.823167,On or near Nightclub,E01016952,Brighton and Hove 027A,Suspect charged
1060786,5a85fb097731fa8955e5222fd317de3fa9ac560580b84a...,2024-10,Sussex Police,Sussex Police,-0.150353,50.823643,On or near Parking Area,E01016952,Brighton and Hove 027A,Unable to prosecute suspect
1060787,ccb98f929bcb661266cd8be27832ae63b9a1ded03323ab...,2024-10,Sussex Police,Sussex Police,-0.135642,50.830460,On or near Supermarket,E01016964,Brighton and Hove 027C,Unable to prosecute suspect
1060788,e82cc5fa61154ce4084ee315b381c687511aca9bcac2f7...,2024-10,Sussex Police,Sussex Police,NaN,NaN,No location,NaN,NaN,Investigation complete; no suspect identified

In [8]:
## 2. INITIAL DATA INSPECTION

In [9]:
'''Inspecting columns and rows of both datasets'''
print("Crime data shape:", crime_df.shape)
print("Outcomes data shape:", outcomes_df.shape)

Crime data shape: (1226064, 12)
Outcomes data shape: (1060789, 10)

In [10]:
crime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1226064 entries, 0 to 1226063
Data columns (total 12 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Crime ID               1071051 non-null  object
 1   Month                  1226064 non-null  object
 2   Reported by            1226064 non-null  object
 3   Falls within           1226064 non-null  object
 4   Longitude              1202896 non-null  float64
 5   Latitude               1202896 non-null  float64
 6   Location               1226064 non-null  object
 7   LSOA code              1202893 non-null  object
 8   LSOA name              1202893 non-null  object
 9   Crime type             1226064 non-null  object
 10  Last outcome category  1071051 non-null  object
 11  Context                0 non-null        float64
dtypes: float64(3), object(9)
memory usage: 112.2+ MB

In [11]:
outcomes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1060789 entries, 0 to 1060788
Data columns (total 10 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Crime ID      1060789 non-null  object
 1   Month         1060789 non-null  object
 2   Reported by   1060789 non-null  object
 3   Falls within  1060789 non-null  object
 4   Longitude     1041869 non-null  float64
 5   Latitude      1041869 non-null  float64
 6   Location      1060789 non-null  object
 7   LSOA code     1041867 non-null  object
 8   LSOA name     1041867 non-null  object
 9   Outcome type  1060789 non-null  object
dtypes: float64(2), object(8)
memory usage: 80.9+ MB

In [12]:
# 3. INITIAL DATA QUALITY CHECKS

# Before merging the datasets, the candidate join field (`Crime ID`) was assessed for missing values and duplicates.
# This was necessary to understand whether matching on `Crime ID` was appropriate and to avoid incorrect merges.

# The DataFrame index was not used as a merge key because it only represents row position within each CSV and is not a shared identifier across separate files.

In [13]:
'''Missing Crime IDs'''
print("Crime ID nulls in crime_df:", crime_df["Crime ID"].isna().sum())
print("Crime ID nulls in outcomes_df:", outcomes_df["Crime ID"].isna().sum())

Crime ID nulls in crime_df: 155013
Crime ID nulls in outcomes_df: 0

In [14]:
'''Duplicate rows in both datasets'''
print("Duplicate rows in crime_df:", crime_df.duplicated().sum())
print("Duplicate rows in outcomes_df:", outcomes_df.duplicated().sum())

Duplicate rows in crime_df: 35840
Duplicate rows in outcomes_df: 6394

In [15]:
'''Duplicate Crime IDs'''
print("Duplicate Crime IDs in crime_df:", crime_df["Crime ID"].duplicated().sum())
print("Duplicate Crime IDs in outcomes_df:", outcomes_df["Crime ID"].duplicated().sum())

Duplicate Crime IDs in crime_df: 155143
Duplicate Crime IDs in outcomes_df: 26659

In [16]:
# This section displays rows where `Crime ID` appears more than once,
# in order to understand whether repeated values represent genuine repeated records, duplicate rows, or possible one-to-many relationships.

In [17]:
'''Investigating Duplicates'''
crime_dupes = crime_df[crime_df["Crime ID"].duplicated(keep=False)]
outcome_dupes = outcomes_df[outcomes_df["Crime ID"].duplicated(keep=False)]

In [18]:
crime_dupes

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
4,NaN,2024-09,Sussex Police,Sussex Police,-0.224424,50.839417,On or near St Louie Close,E01031350,Adur 001B,Anti-social behaviour,NaN,NaN
10,NaN,2024-09,Sussex Police,Sussex Police,-0.241628,50.842340,On or near Downland Close,E01031351,Adur 001C,Anti-social behaviour,NaN,NaN
11,NaN,2024-09,Sussex Police,Sussex Police,-0.245903,50.841586,On or near Kingston Broadway,E01031351,Adur 001C,Anti-social behaviour,NaN,NaN
12,NaN,2024-09,Sussex Police,Sussex Police,-0.247205,50.842469,On or near Shopping Area,E01031351,Adur 001C,Anti-social behaviour,NaN,NaN
13,NaN,2024-09,Sussex Police,Sussex Police,-0.245903,50.841586,On or near Kingston Broadway,E01031351,Adur 001C,Anti-social behaviour,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1225940,NaN,2024-10,Surrey Police,Surrey Police,-0.555867,51.299336,On or near Meadow View,E01034297,Woking 011G,Anti-social behaviour,NaN,NaN
1225941,NaN,2024-10,Surrey Police,Surrey Police,-0.555321,51.298439,On or near Meadow View,E01034297,Woking 011G,Anti-social behaviour,NaN,NaN
1225945,NaN,2024-10,Surrey Police,Surrey Police,-0.627282,51.310087,On or near Raynes Close,E01030944,Woking 012A,Anti-social behaviour,NaN,NaN
1225953,NaN,2024-10,Surrey Police,Surrey Police,-0.625916,51.316410,On or near Ivydene,E01030978,Woking 012C,Anti-social behaviour,NaN,NaN
1225968,NaN,2024-10,Surrey Police,Surrey Police,-0.582787,51.289216,On or near Prey Heath Road,E01030987,Woking 012E,Anti-social behaviour,NaN,NaN

In [19]:
# 4. MERGING THE DATA

# The crime and outcomes datasets were merged using `Crime ID` as the best available record identifier.
# A left join was used to retain all crime records and attach outcome information where available.

In [20]:
'''Merging Crime and Outcomes Data'''
merged_df = pd.merge(
    crime_df,
    outcomes_df,
    on="Crime ID", #using Crime ID to merge the two files
    how="left",
    suffixes=("_crime", "_outcome") # instead of 'x' and 'y' to be more clear
)

In [21]:
merged_df #checking merged result

,Crime ID,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,Crime type,...,Context,Month_outcome,Reported by_outcome,Falls within_outcome,Longitude_outcome,Latitude_outcome,Location_outcome,LSOA code_outcome,LSOA name_outcome,Outcome type
0,71559ac1da22a7f37aa9903b221cf37d0421161dd0af10...,2024-09,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Burglary,...,NaN,2024-11,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Investigation complete; no suspect identified
1,1b283393948b1eab734d27e1a61ceffe11f9ace552775e...,2024-09,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,...,NaN,2024-11,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Unable to prosecute suspect
2,81a36ac50ea09f197158277c7000c2dd4dfac74707019d...,2024-09,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Violence and sexual offences,...,NaN,2024-09,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Unable to prosecute suspect
3,0db45b92c423603a27a97bae30f5f919ce1b2d177eeb0e...,2024-09,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,...,NaN,2024-11,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Unable to prosecute suspect
4,NaN,2024-09,Sussex Police,Sussex Police,-0.224424,50.839417,On or near St Louie Close,E01031350,Adur 001B,Anti-social behaviour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1249934,43a231da6279502eccd41e20ccd071de349cb80e17295f...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,...,NaN,2024-12,Surrey Police,Surrey Police,NaN,NaN,No location,NaN,NaN,Further action is not in the public interest
1249935,43a231da6279502eccd41e20ccd071de349cb80e17295f...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,...,NaN,2025-02,Surrey Police,Surrey Police,NaN,NaN,No location,NaN,NaN,Further investigation is not in the public int...
1249936,50e8d9e3ad37b272a9780873ee36a0a65fe0415f7d9bb4...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,...,NaN,2024-11,Surrey Police,Surrey Police,NaN,NaN,No location,NaN,NaN,Unable to prosecute suspect
1249937,105bbaa7db4b8c9f69e266234bd1de904dfa375f21f89c...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,...,NaN,2024-11,Surrey Police,Surrey Police,NaN,NaN,No location,NaN,NaN,Action to be taken by another organisation
1249938,4480d7f25eb658fd55832b05598f8380b50c03af5a7a6d...,2024-10,Surrey Police,Surrey Police,NaN,NaN,No Location,NaN,NaN,Other crime,...,NaN,2025-05,Surrey Police,Surrey Police,NaN,NaN,No location,NaN,NaN,Unable to prosecute suspect

In [22]:
# 5. DATA STRUCTURE OVERVIEW

In [23]:
merged_df.describe()

,Longitude_crime,Latitude_crime,Context,Longitude_outcome,Latitude_outcome
count,1.226284e+06,1.226284e+06,0.0,957772.000000,957772.000000
mean,-7.258705e-01,5.121915e+01,NaN,-0.737661,51.223429
std,5.130993e-01,3.826828e-01,NaN,0.510593,0.385728
min,-6.581064e+00,5.057788e+01,NaN,-6.339279,50.577883
25%,-1.136641e+00,5.085380e+01,NaN,-1.148903,50.854781
50%,-7.564480e-01,5.121007e+01,NaN,-0.760427,51.215510
75%,-3.671030e-01,5.145869e+01,NaN,-0.383029,51.467310
max,9.611730e-01,5.483311e+01,NaN,0.961173,54.833107

In [24]:
merged_df.shape

(1249939, 21)

In [25]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1249939 entries, 0 to 1249938
Data columns (total 21 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Crime ID               1094926 non-null  object
 1   Month_crime            1249939 non-null  object
 2   Reported by_crime      1249939 non-null  object
 3   Falls within_crime     1249939 non-null  object
 4   Longitude_crime        1226284 non-null  float64
 5   Latitude_crime         1226284 non-null  float64
 6   Location_crime         1249939 non-null  object
 7   LSOA code_crime        1226281 non-null  object
 8   LSOA name_crime        1226281 non-null  object
 9   Crime type             1249939 non-null  object
 10  Last outcome category  1094926 non-null  object
 11  Context                0 non-null        float64
 12  Month_outcome          975173 non-null   object
 13  Reported by_outcome    975173 non-null   object
 14  Falls within_outcome   975173 non-null   object
 15  Longitude_outcome      957772 non-null   float64
 16  Latitude_outcome       957772 non-null   float64
 17  Location_outcome       975173 non-null   object
 18  LSOA code_outcome      957770 non-null   object
 19  LSOA name_outcome      957770 non-null   object
 20  Outcome type           975173 non-null   object
dtypes: float64(5), object(16)
memory usage: 200.3+ MB

In [26]:
for column in merged_df.columns:
    print(column)

Crime ID
Month_crime
Reported by_crime
Falls within_crime
Longitude_crime
Latitude_crime
Location_crime
LSOA code_crime
LSOA name_crime
Crime type
Last outcome category
Context
Month_outcome
Reported by_outcome
Falls within_outcome
Longitude_outcome
Latitude_outcome
Location_outcome
LSOA code_outcome
LSOA name_outcome
Outcome type

In [27]:
# 6. DATA QUALITY CHECKS

#After merging, the dataset was checked for:
#- duplicate rows
#- repeated `Crime ID` values
#- null values
#- duplicated information across crime and outcome columns

In [28]:
## 6.1 Checking for Duplicates

In [29]:
'''Crime ID duplicates'''
print("Exact duplicate rows in merged_df:", merged_df.duplicated().sum())
print("Duplicate Crime IDs in merged_df:", merged_df["Crime ID"].duplicated().sum())

Exact duplicate rows in merged_df: 40821
Duplicate Crime IDs in merged_df: 179018

In [30]:
'''Comparing Duplicate Column Pairs'''
# The merged dataset contains paired columns from the crime and outcomes files, such as month, location coordinates, police force, and location.
# These columns are compared to determine whether one version can be retained.

comparison_results = {
    "Month match": (merged_df["Month_crime"] == merged_df["Month_outcome"]).value_counts(dropna=False),
    "Reported by match": (merged_df["Reported by_crime"] == merged_df["Reported by_outcome"]).value_counts(dropna=False),
    "Falls within match": (merged_df["Falls within_crime"] == merged_df["Falls within_outcome"]).value_counts(dropna=False),
    "Longitude match": (merged_df["Longitude_crime"] == merged_df["Longitude_outcome"]).value_counts(dropna=False),
    "Latitude match": (merged_df["Latitude_crime"] == merged_df["Latitude_outcome"]).value_counts(dropna=False),
    "Location match": (merged_df["Location_crime"] == merged_df["Location_outcome"]).value_counts(dropna=False),
    "LSOA code match": (merged_df["LSOA code_crime"] == merged_df["LSOA code_outcome"]).value_counts(dropna=False),
    "LSOA name match": (merged_df["LSOA name_crime"] == merged_df["LSOA name_outcome"]).value_counts(dropna=False)
}

comparison_results

{'Month match': False    839023
 True     410916
 Name: count, dtype: int64,
 'Reported by match': True     975173
 False    274766
 Name: count, dtype: int64,
 'Falls within match': True     975173
 False    274766
 Name: count, dtype: int64,
 'Longitude match': True     957772
 False    292167
 Name: count, dtype: int64,
 'Latitude match': True     957772
 False    292167
 Name: count, dtype: int64,
 'Location match': True     939694
 False    310245
 Name: count, dtype: int64,
 'LSOA code match': True     957770
 False    292169
 Name: count, dtype: int64,
 'LSOA name match': True     957770
 False    292169
 Name: count, dtype: int64}

In [31]:
'''Understanding Crime ID duplicates'''
duplicate_crime_ids = merged_df["Crime ID"].value_counts()

duplicate_crime_ids = duplicate_crime_ids[duplicate_crime_ids > 1]

duplicate_crime_ids

Crime ID
bd24eedce4cae3ffba65eb9c567b4e493c221f02aa9b2abff3e839c55fa6a1d4    12
ea9feea14202dee07b47d1c262d57452467b95bbfeef43a2f4f6b5c56e625365    10
6fa0062bf3fa3a2f2a6b8114ee45313f315e628771c1d91c777b1e521b5f9c57    10
c911193fbff240ab4c3c5050536042c32abd45ebdf717d5825c24c012cc60564     9
6888a94efce5a51cc1936c73b5c130712ae5172fa9a9303eaf92375bedf6158f     9
                                                                    ..
5aeebd8586d3ed9f982a30fc003c772d61a374e3e1fb4d3e63fc4e56bd0dab46     2
05955d3dacd932431d9457cc9aaf9a010e256aa5063ddaec4ace8a3d0b1c5639     2
97a78bccd2433c85370df567887d533e6d5c8d426de0579ee974a9ef1f0d1f53     2
6e4179532e6a1c9d9a9e8e50f336e3214f1acb6e4ba78d1cd99dd3c79a99aa09     2
dd8ffcdb2a05213a6357dfd66ea85b8b5a4e9b752c3045deac4f67341542c71f     2
Name: count, Length: 22135, dtype: int64

In [32]:
merged_df[merged_df["Crime ID"] == "5aeebd8586d3ed9f982a30fc003c772d61a374e3e1fb4d3e63fc4e56bd0dab46"]

,Crime ID,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,Crime type,...,Context,Month_outcome,Reported by_outcome,Falls within_outcome,Longitude_outcome,Latitude_outcome,Location_outcome,LSOA code_outcome,LSOA name_outcome,Outcome type
800933,5aeebd8586d3ed9f982a30fc003c772d61a374e3e1fb4d...,2024-05,Surrey Police,Surrey Police,-0.45515,51.424178,On or near Fairways,E01030705,Spelthorne 005E,Burglary,...,NaN,2024-07,Surrey Police,Surrey Police,-0.45515,51.424178,On or near Fairways,E01030705,Spelthorne 005E,Suspect charged
800934,5aeebd8586d3ed9f982a30fc003c772d61a374e3e1fb4d...,2024-05,Surrey Police,Surrey Police,-0.45515,51.424178,On or near Fairways,E01030705,Spelthorne 005E,Burglary,...,NaN,2024-07,Surrey Police,Surrey Police,-0.45515,51.424178,On or near Fairways,E01030705,Spelthorne 005E,Suspect charged

In [33]:
duplicate_rows = merged_df[
    merged_df["Crime ID"].isin(duplicate_crime_ids.index)
]

duplicate_rows.sort_values("Crime ID")

,Crime ID,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,Crime type,...,Context,Month_outcome,Reported by_outcome,Falls within_outcome,Longitude_outcome,Latitude_outcome,Location_outcome,LSOA code_outcome,LSOA name_outcome,Outcome type
1055513,00001462ecf1f92810cb42f4dcff59c9e04ac58faa0c00...,2025-10,Sussex Police,Sussex Police,-0.136033,50.820645,On or near Steine Street,E01016941,Brighton and Hove 030A,Violence and sexual offences,...,NaN,2025-10,Sussex Police,Sussex Police,-0.136033,50.820645,On or near Steine Street,E01016941,Brighton and Hove 030A,Unable to prosecute suspect
1055512,00001462ecf1f92810cb42f4dcff59c9e04ac58faa0c00...,2025-10,Sussex Police,Sussex Police,-0.136033,50.820645,On or near Steine Street,E01016941,Brighton and Hove 030A,Violence and sexual offences,...,NaN,2025-12,Sussex Police,Sussex Police,-0.136033,50.820645,On or near Steine Street,E01016941,Brighton and Hove 030A,Unable to prosecute suspect
1074112,000319f84b2491a261f8317a2a778fdf3035e7985024be...,2025-10,Thames Valley Police,Thames Valley Police,-0.974514,51.467665,On or near Church Street,E01016364,Reading 003A,Shoplifting,...,NaN,2025-11,Thames Valley Police,Thames Valley Police,-0.974514,51.467665,On or near Church Street,E01016364,Reading 003A,Suspect charged
1074113,000319f84b2491a261f8317a2a778fdf3035e7985024be...,2025-10,Thames Valley Police,Thames Valley Police,-0.974514,51.467665,On or near Church Street,E01016364,Reading 003A,Shoplifting,...,NaN,2025-11,Thames Valley Police,Thames Valley Police,-0.974514,51.467665,On or near Church Street,E01016364,Reading 003A,Suspect charged
1055181,0005139ad6792be342d313f401632569fdb881e2f4acd8...,2025-10,Sussex Police,Sussex Police,-0.141505,50.823691,On or near King Place,E01016969,Brighton and Hove 027E,Violence and sexual offences,...,NaN,2025-12,Sussex Police,Sussex Police,-0.141505,50.823691,On or near King Place,E01016969,Brighton and Hove 027E,Investigation complete; no suspect identified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932417,fffa45d464acc60a7cdb613c37dbaf3e1cd50570fd7260...,2025-05,Thames Valley Police,Thames Valley Police,-0.567109,51.501440,On or near Petrol Station,E01035249,Slough 011H,Shoplifting,...,NaN,2025-05,Thames Valley Police,Thames Valley Police,-0.567109,51.501440,On or near Petrol Station,E01035249,Slough 011H,Investigation complete; no suspect identified
225422,fffa7c37087f609b43f528b2c8579c351dd8277393762a...,2024-08,Sussex Police,Sussex Police,0.576667,50.908327,On or near Greenacres,E01021089,Rother 005C,Other crime,...,NaN,2024-09,Sussex Police,Sussex Police,0.576667,50.908327,On or near Greenacres,E01021089,Rother 005C,Suspect charged
225423,fffa7c37087f609b43f528b2c8579c351dd8277393762a...,2024-08,Sussex Police,Sussex Police,0.576667,50.908327,On or near Greenacres,E01021089,Rother 005C,Other crime,...,NaN,2024-11,Sussex Police,Sussex Police,0.576667,50.908327,On or near Greenacres,E01021089,Rother 005C,Suspect charged
1009481,ffff2f040fe908d803a52c3c48c3c07f2dee3c925d5481...,2025-03,Surrey Police,Surrey Police,-0.328496,51.296914,On or near Queen Annes Court,E01030550,Mole Valley 003C,Violence and sexual offences,...,NaN,2025-10,Surrey Police,Surrey Police,-0.328496,51.296914,On or near Queen Annes Court,E01030550,Mole Valley 003C,Suspect charged
1009480,ffff2f040fe908d803a52c3c48c3c07f2dee3c925d5481...,2025-03,Surrey Police,Surrey Police,-0.328496,51.296914,On or near Queen Annes Court,E01030550,Mole Valley 003C,Violence and sexual offences,...,NaN,2025-10,Surrey Police,Surrey Police,-0.328496,51.296914,On or near Queen Annes Court,E01030550,Mole Valley 003C,Suspect charged

In [34]:
grouped_merged_df = merged_df.groupby("Crime ID").nunique().sort_values("Crime type", ascending=False)
grouped_merged_df

,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,Crime type,Last outcome category,Context,Month_outcome,Reported by_outcome,Falls within_outcome,Longitude_outcome,Latitude_outcome,Location_outcome,LSOA code_outcome,LSOA name_outcome,Outcome type
Crime ID,,,,,,,,,,,,,,,,,,,,
0000037ec6990710a1aa2e62eeb32364e411a8eed372d41772ce282b006d4933,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
aa9030bfcec4f3ff3062e060a6c8e8a388304571b519ab8a3787846b92d883e2,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1
aa90895767a4dee7ea8011104745b9cdc6c486f38456f28d3be4b572c2f98d9d,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1
aa908d7aa618e6c926ff8fbe132f65fe208b1057c715d8eae67feb2c443abfad,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1
aa90b0ddb43bcb07e6071544a03ffbf33947bfffe4cf63d6d05e52a473d6f1b3,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55491ab7dab3ad543ff63c5f7a6db30c11e862f0728257f97af67661c4e0d3c2,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
55491f916f4f840ec5541476dde1bf5078874d9caa2041b7bd8a53a3610e2122,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1
55492307fef219550c74893bbf2637d776f8c5567b79686c7581b9a43f3c7bca,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1
554927badb61bd9ac58d4e7fbeca5319b9db43be38e0cd56ca7eb52c38041391,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1
ffffe2d8508e23732ebef55410398b6cf26ef6dea524668682f00fe82e6f2c56,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1

In [35]:
'''Summary table of repeated Crime IDs'''
duplicate_summary = (
    merged_df.groupby("Crime ID")
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
)

duplicate_summary

                                                  Crime ID  count
791511   bd24eedce4cae3ffba65eb9c567b4e493c221f02aa9b2a...     12
981970   ea9feea14202dee07b47d1c262d57452467b95bbfeef43...     10
467425   6fa0062bf3fa3a2f2a6b8114ee45313f315e628771c1d9...     10
437946   6888a94efce5a51cc1936c73b5c130712ae5172fa9a930...      9
841216   c911193fbff240ab4c3c5050536042c32abd45ebdf717d...      9
...                                                    ...    ...
360629   5627ff66dd5412e2f13fa5bb4f0c95c32beef3c7600eab...      1
360630   562800421f5918e127fb2b962de540aa184a225a8d0124...      1
360631   562807762a78c162677407768ba2e07939a0d6a02e2dba...      1
360632   56281b6bd58cf24a9f7e6b14728933a3f02ef2a05f0bc5...      1
1070919  ffffe2d8508e23732ebef55410398b6cf26ef6dea52466...      1

[1070920 rows x 2 columns]

In [36]:
# 6.2 - Checking for null values

In [37]:
'''Nulls by column'''
merged_df.isnull().sum().sort_values(ascending=False)

Context                  1249939
LSOA name_outcome         292169
LSOA code_outcome         292169
Latitude_outcome          292167
Longitude_outcome         292167
Outcome type              274766
Location_outcome          274766
Falls within_outcome      274766
Reported by_outcome       274766
Month_outcome             274766
Crime ID                  155013
Last outcome category     155013
LSOA name_crime            23658
LSOA code_crime            23658
Latitude_crime             23655
Longitude_crime            23655
Month_crime                    0
Crime type                     0
Location_crime                 0
Falls within_crime             0
Reported by_crime              0
dtype: int64

In [38]:
'''Comparing null values to non-null values'''
null_summary = pd.DataFrame({
    "total_values": merged_df.shape[0],
    "null_values": merged_df.isnull().sum(),
    "non_null_values": merged_df.notnull().sum(),
    "percent_null": merged_df.isnull().mean() * 100
})

null_summary

,total_values,null_values,non_null_values,percent_null
Crime ID,1249939,155013,1094926,12.401645
Month_crime,1249939,0,1249939,0.000000
Reported by_crime,1249939,0,1249939,0.000000
Falls within_crime,1249939,0,1249939,0.000000
Longitude_crime,1249939,23655,1226284,1.892492
Latitude_crime,1249939,23655,1226284,1.892492
Location_crime,1249939,0,1249939,0.000000
LSOA code_crime,1249939,23658,1226281,1.892732
LSOA name_crime,1249939,23658,1226281,1.892732
Crime type,1249939,0,1249939,0.000000
Last outcome category,1249939,155013,1094926,12.401645
Context,1249939,1249939,0,100.000000
Month_outcome,1249939,274766,975173,21.982353
Reported by_outcome,1249939,274766,975173,21.982353
Falls within_outcome,1249939,274766,975173,21.982353
Longitude_outcome,1249939,292167,957772,23.374501
Latitude_outcome,1249939,292167,957772,23.374501
Location_outcome,1249939,274766,975173,21.982353
LSOA code_outcome,1249939,292169,957770,23.374661
LSOA name_outcome,1249939,292169,957770,23.374661
Outcome type,1249939,274766,975173,21.982353

In [39]:
# Checking for categorical consistency

In [40]:
merged_df["Crime type"].value_counts() #looking out for any unexpected categories or spelling errors

Crime type
Violence and sexual offences    467010
Anti-social behaviour           155013
Shoplifting                     123440
Public order                    103402
Criminal damage and arson        93253
Other theft                      86525
Vehicle crime                    62890
Burglary                         44212
Drugs                            38885
Other crime                      26056
Possession of weapons            14505
Bicycle theft                    13820
Theft from the person            10538
Robbery                          10390
Name: count, dtype: int64

In [41]:
merged_df["Outcome type"].value_counts() #looking out for any unexpected categories or spelling errors

Outcome type
Unable to prosecute suspect                            404929
Investigation complete; no suspect identified          403872
Suspect charged                                         77771
Local resolution                                        42613
Action to be taken by another organisation              17992
Offender given a caution                                10400
Further investigation is not in the public interest      8149
Further action is not in the public interest             4425
Formal action is not in the public interest              4090
Suspect charged as part of another case                   688
Offender given penalty notice                             242
Offender given a drugs possession warning                   2
Name: count, dtype: int64

In [42]:
'''Verifying police forces'''
merged_df["Falls within_crime"].value_counts() #should only see the 4 police forces

Falls within_crime
Thames Valley Police      400723
Hampshire Constabulary    339564
Sussex Police             328029
Surrey Police             181623
Name: count, dtype: int64

In [43]:
'''Checking date coverage'''
merged_df["Month_crime"].value_counts().sort_index() #confirming Jan 2024 – Dec 2025 exists

Month_crime
2024-01    49691
2024-02    47516
2024-03    51715
2024-04    51651
2024-05    55528
2024-06    55757
2024-07    57471
2024-08    55447
2024-09    50752
2024-10    54384
2024-11    51374
2024-12    47256
2025-01    47598
2025-02    45579
2025-03    53502
2025-04    52364
2025-05    55734
2025-06    53625
2025-07    59587
2025-08    55608
2025-09    51470
2025-10    52001
2025-11    48606
2025-12    45723
Name: count, dtype: int64

In [44]:
'''Checking coordinate ranges'''
merged_df[["Longitude_crime","Latitude_crime"]].describe()

       Longitude_crime  Latitude_crime
count     1.226284e+06    1.226284e+06
mean     -7.258705e-01    5.121915e+01
std       5.130993e-01    3.826828e-01
min      -6.581064e+00    5.057788e+01
25%      -1.136641e+00    5.085380e+01
50%      -7.564480e-01    5.121007e+01
75%      -3.671030e-01    5.145869e+01
max       9.611730e-01    5.483311e+01

In [45]:
# 7. DATA CLEANING

In [46]:
# creating flags for analysis
merged_df["has_crime_id"] = merged_df["Crime ID"].notnull()

# adding row-level coordinate validity flags
merged_df["has_valid_coords_crime"] = (
    merged_df["Longitude_crime"].notnull() |
    merged_df["Latitude_crime"].notnull()
)

merged_df["has_valid_lsoa_for_mapping_crime"] = (
    merged_df["Longitude_crime"].notnull() &
    merged_df["Latitude_crime"].notnull() &
    merged_df["LSOA name_crime"].notnull() &
    merged_df["LSOA code_crime"].notnull()
)

merged_df["has_valid_coords_outcome"] = (
    merged_df["Longitude_outcome"].notnull() |
    merged_df["Latitude_outcome"].notnull()
)

merged_df["has_valid_lsoa_for_mapping_outcome"] = (
    merged_df["Longitude_outcome"].notnull() &
    merged_df["Latitude_outcome"].notnull() &
    merged_df["LSOA name_outcome"].notnull() &
    merged_df["LSOA code_outcome"].notnull()
)

merged_df["has_outcome"] = merged_df["Outcome type"].isnull() #outcome indicator column

In [47]:
'''Clean Crime ID column created'''
merged_df["crime_id_clean"] = pd.factorize(merged_df["Crime ID"])[0] + 1

'''How many times each Crime ID appears'''
merged_df["crime_id_count"] = merged_df.groupby("Crime ID")["Crime ID"].transform("count")

In [48]:
'''Coordinate range'''
merged_df = merged_df[
    (merged_df["Latitude_crime"].between(50, 52.5)) &
    (merged_df["Longitude_crime"].between(-2, 1))
]

In [49]:
'''Date Formatting for Month'''

# converting the `Month` columns into datetime format so time-based analysis can be performed
merged_df.loc[:, "Month_crime"] = pd.to_datetime(merged_df["Month_crime"])
merged_df.loc[:, "Month_outcome"] = pd.to_datetime(merged_df["Month_outcome"])

In [50]:
merged_df

,Crime ID,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,Crime type,...,LSOA name_outcome,Outcome type,has_crime_id,has_valid_coords_crime,has_valid_lsoa_for_mapping_crime,has_valid_coords_outcome,has_valid_lsoa_for_mapping_outcome,has_outcome,crime_id_clean,crime_id_count
0,71559ac1da22a7f37aa9903b221cf37d0421161dd0af10...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Burglary,...,Adur 001A,Investigation complete; no suspect identified,True,True,True,True,True,False,1,1.0
1,1b283393948b1eab734d27e1a61ceffe11f9ace552775e...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,...,Adur 001A,Unable to prosecute suspect,True,True,True,True,True,False,2,1.0
2,81a36ac50ea09f197158277c7000c2dd4dfac74707019d...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Violence and sexual offences,...,Adur 001A,Unable to prosecute suspect,True,True,True,True,True,False,3,1.0
3,0db45b92c423603a27a97bae30f5f919ce1b2d177eeb0e...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,...,Adur 001A,Unable to prosecute suspect,True,True,True,True,True,False,4,1.0
4,NaN,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.224424,50.839417,On or near St Louie Close,E01031350,Adur 001B,Anti-social behaviour,...,NaN,NaN,False,True,True,False,False,True,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1249836,af4fd2b4ca5a89c6b7daeac2aad690b05cdaa019a4f215...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.562550,51.298465,On or near Westfield Road,E01030986,Woking 012D,Shoplifting,...,Woking 012D,Unable to prosecute suspect,True,True,True,True,True,False,1070825,2.0
1249837,af4fd2b4ca5a89c6b7daeac2aad690b05cdaa019a4f215...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.562550,51.298465,On or near Westfield Road,E01030986,Woking 012D,Shoplifting,...,Woking 012D,Investigation complete; no suspect identified,True,True,True,True,True,False,1070825,2.0
1249838,NaN,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.582787,51.289216,On or near Prey Heath Road,E01030987,Woking 012E,Anti-social behaviour,...,NaN,NaN,False,True,True,False,False,True,0,NaN
1249839,af9e5b58b52dadbc5e4fe572e61fa6c680dae892ca1799...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.575237,51.295932,On or near B380,E01030987,Woking 012E,Drugs,...,Woking 012E,Investigation complete; no suspect identified,True,True,True,True,True,False,1070826,1.0
1249840,12d1ff7ba630d957d1dcce1ca8f08b5033e12755776475...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.575237,51.295932,On or near B380,E01030987,Woking 012E,Drugs,...,Woking 012E,Investigation complete; no suspect identified,True,True,True,True,True,False,1070827,1.0

In [51]:
'''Preparing Map Data - Crime Points'''

# Create geometry in original coordinate system (WGS84)
merged_df.loc[:, "geometry_wgs84"] = gpd.points_from_xy(
    merged_df["Longitude_crime"],
    merged_df["Latitude_crime"],
    crs="EPSG:4326"
)

# Convert to a GeoSeries and reproject to Web Mercator for basemap compatibility
geometry_3857 = gpd.GeoSeries(merged_df["geometry_wgs84"], crs="EPSG:4326").to_crs(epsg=3857)

# Store reprojected geometry back into merged_df
merged_df.loc[:, "geometry_3857"] = geometry_3857

merged_df

/var/folders/js/533b3q0s69x9mn1hskhqczpm0000gn/T/ipykernel_71850/3717395139.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df.loc[:, "geometry_wgs84"] = gpd.points_from_xy(
/var/folders/js/533b3q0s69x9mn1hskhqczpm0000gn/T/ipykernel_71850/3717395139.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df.loc[:, "geometry_3857"] = geometry_3857

,Crime ID,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,Crime type,...,has_crime_id,has_valid_coords_crime,has_valid_lsoa_for_mapping_crime,has_valid_coords_outcome,has_valid_lsoa_for_mapping_outcome,has_outcome,crime_id_clean,crime_id_count,geometry_wgs84,geometry_3857
0,71559ac1da22a7f37aa9903b221cf37d0421161dd0af10...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Burglary,...,True,True,True,True,True,False,1,1.0,POINT (-0.22768 50.83608),POINT (-25344.776 6592348.528)
1,1b283393948b1eab734d27e1a61ceffe11f9ace552775e...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,...,True,True,True,True,True,False,2,1.0,POINT (-0.22646 50.83636),POINT (-25209.078 6592399.117)
2,81a36ac50ea09f197158277c7000c2dd4dfac74707019d...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Violence and sexual offences,...,True,True,True,True,True,False,3,1.0,POINT (-0.22768 50.83608),POINT (-25344.776 6592348.528)
3,0db45b92c423603a27a97bae30f5f919ce1b2d177eeb0e...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,...,True,True,True,True,True,False,4,1.0,POINT (-0.22646 50.83636),POINT (-25209.078 6592399.117)
4,NaN,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.224424,50.839417,On or near St Louie Close,E01031350,Adur 001B,Anti-social behaviour,...,False,True,True,False,False,True,0,NaN,POINT (-0.22442 50.83942),POINT (-24982.765 6592937.455)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1249836,af4fd2b4ca5a89c6b7daeac2aad690b05cdaa019a4f215...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.562550,51.298465,On or near Westfield Road,E01030986,Woking 012D,Shoplifting,...,True,True,True,True,True,False,1070825,2.0,POINT (-0.56255 51.29846),POINT (-62622.78 6674259.508)
1249837,af4fd2b4ca5a89c6b7daeac2aad690b05cdaa019a4f215...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.562550,51.298465,On or near Westfield Road,E01030986,Woking 012D,Shoplifting,...,True,True,True,True,True,False,1070825,2.0,POINT (-0.56255 51.29846),POINT (-62622.78 6674259.508)
1249838,NaN,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.582787,51.289216,On or near Prey Heath Road,E01030987,Woking 012E,Anti-social behaviour,...,False,True,True,False,False,True,0,NaN,POINT (-0.58279 51.28922),POINT (-64875.552 6672613.018)
1249839,af9e5b58b52dadbc5e4fe572e61fa6c680dae892ca1799...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.575237,51.295932,On or near B380,E01030987,Woking 012E,Drugs,...,True,True,True,True,True,False,1070826,1.0,POINT (-0.57524 51.29593),POINT (-64035.09 6673808.555)
1249840,12d1ff7ba630d957d1dcce1ca8f08b5033e12755776475...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.575237,51.295932,On or near B380,E01030987,Woking 012E,Drugs,...,True,True,True,True,True,False,1070827,1.0,POINT (-0.57524 51.29593),POINT (-64035.09 6673808.555)

In [52]:
'''Preparing map data: LSOA Hotspots'''

# creating LSOA-level aggregated hotspot metrics

lsoa_summary_crime = (
    merged_df[merged_df["has_valid_lsoa_for_mapping_crime"]]
    .groupby(["LSOA code_crime", "LSOA name_crime", "Falls within_crime"], as_index=False)
    .agg(
        lsoa_crime_count=("Crime ID", "size"),
        lsoa_mean_longitude_crime=("Longitude_crime", "mean"),
        lsoa_mean_latitude_crime=("Latitude_crime", "mean")
    )
)

# merging LSOA-level metrics back into merged_df

merged_df = merged_df.merge(
    lsoa_summary_crime,
    on=["LSOA code_crime", "LSOA name_crime", "Falls within_crime"],
    how="left"
)

merged_df

,Crime ID,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,Crime type,...,has_valid_coords_outcome,has_valid_lsoa_for_mapping_outcome,has_outcome,crime_id_clean,crime_id_count,geometry_wgs84,geometry_3857,lsoa_crime_count,lsoa_mean_longitude_crime,lsoa_mean_latitude_crime
0,71559ac1da22a7f37aa9903b221cf37d0421161dd0af10...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Burglary,...,True,True,False,1,1.0,POINT (-0.22768 50.83608),POINT (-25344.776 6592348.528),78,-0.227777,50.836884
1,1b283393948b1eab734d27e1a61ceffe11f9ace552775e...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,...,True,True,False,2,1.0,POINT (-0.22646 50.83636),POINT (-25209.078 6592399.117),78,-0.227777,50.836884
2,81a36ac50ea09f197158277c7000c2dd4dfac74707019d...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.227676,50.836076,On or near Orchard Close,E01031349,Adur 001A,Violence and sexual offences,...,True,True,False,3,1.0,POINT (-0.22768 50.83608),POINT (-25344.776 6592348.528),78,-0.227777,50.836884
3,0db45b92c423603a27a97bae30f5f919ce1b2d177eeb0e...,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.226457,50.836363,On or near Manor Hall Road,E01031349,Adur 001A,Violence and sexual offences,...,True,True,False,4,1.0,POINT (-0.22646 50.83636),POINT (-25209.078 6592399.117),78,-0.227777,50.836884
4,NaN,2024-09-01 00:00:00,Sussex Police,Sussex Police,-0.224424,50.839417,On or near St Louie Close,E01031350,Adur 001B,Anti-social behaviour,...,False,False,True,0,NaN,POINT (-0.22442 50.83942),POINT (-24982.765 6592937.455),139,-0.227785,50.842029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226254,af4fd2b4ca5a89c6b7daeac2aad690b05cdaa019a4f215...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.562550,51.298465,On or near Westfield Road,E01030986,Woking 012D,Shoplifting,...,True,True,False,1070825,2.0,POINT (-0.56255 51.29846),POINT (-62622.78 6674259.508),82,-0.565883,51.296190
1226255,af4fd2b4ca5a89c6b7daeac2aad690b05cdaa019a4f215...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.562550,51.298465,On or near Westfield Road,E01030986,Woking 012D,Shoplifting,...,True,True,False,1070825,2.0,POINT (-0.56255 51.29846),POINT (-62622.78 6674259.508),82,-0.565883,51.296190
1226256,NaN,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.582787,51.289216,On or near Prey Heath Road,E01030987,Woking 012E,Anti-social behaviour,...,False,False,True,0,NaN,POINT (-0.58279 51.28922),POINT (-64875.552 6672613.018),197,-0.575194,51.291182
1226257,af9e5b58b52dadbc5e4fe572e61fa6c680dae892ca1799...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.575237,51.295932,On or near B380,E01030987,Woking 012E,Drugs,...,True,True,False,1070826,1.0,POINT (-0.57524 51.29593),POINT (-64035.09 6673808.555),197,-0.575194,51.291182
1226258,12d1ff7ba630d957d1dcce1ca8f08b5033e12755776475...,2024-10-01 00:00:00,Surrey Police,Surrey Police,-0.575237,51.295932,On or near B380,E01030987,Woking 012E,Drugs,...,True,True,False,1070827,1.0,POINT (-0.57524 51.29593),POINT (-64035.09 6673808.555),197,-0.575194,51.291182

In [53]:
'''Checking new columns added are in Dataset'''
new_cols = merged_df.columns.tolist()
new_cols

['Crime ID',
 'Month_crime',
 'Reported by_crime',
 'Falls within_crime',
 'Longitude_crime',
 'Latitude_crime',
 'Location_crime',
 'LSOA code_crime',
 'LSOA name_crime',
 'Crime type',
 'Last outcome category',
 'Context',
 'Month_outcome',
 'Reported by_outcome',
 'Falls within_outcome',
 'Longitude_outcome',
 'Latitude_outcome',
 'Location_outcome',
 'LSOA code_outcome',
 'LSOA name_outcome',
 'Outcome type',
 'has_crime_id',
 'has_valid_coords_crime',
 'has_valid_lsoa_for_mapping_crime',
 'has_valid_coords_outcome',
 'has_valid_lsoa_for_mapping_outcome',
 'has_outcome',
 'crime_id_clean',
 'crime_id_count',
 'geometry_wgs84',
 'geometry_3857',
 'lsoa_crime_count',
 'lsoa_mean_longitude_crime',
 'lsoa_mean_latitude_crime']

In [54]:
'''Exporting preprocessed data to .csv'''
merged_df.to_csv("Crimes_with_Outcomes_2024_2025.csv", index=False)

In [55]:
'''Checking success'''
df = pd.read_csv("Crimes_with_Outcomes_2024_2025.csv")
print(df.columns)

Index(['Crime ID', 'Month_crime', 'Reported by_crime', 'Falls within_crime',
       'Longitude_crime', 'Latitude_crime', 'Location_crime',
       'LSOA code_crime', 'LSOA name_crime', 'Crime type',
       'Last outcome category', 'Context', 'Month_outcome',
       'Reported by_outcome', 'Falls within_outcome', 'Longitude_outcome',
       'Latitude_outcome', 'Location_outcome', 'LSOA code_outcome',
       'LSOA name_outcome', 'Outcome type', 'has_crime_id',
       'has_valid_coords_crime', 'has_valid_lsoa_for_mapping_crime',
       'has_valid_coords_outcome', 'has_valid_lsoa_for_mapping_outcome',
       'has_outcome', 'crime_id_clean', 'crime_id_count', 'geometry_wgs84',
       'geometry_3857', 'lsoa_crime_count', 'lsoa_mean_longitude_crime',
       'lsoa_mean_latitude_crime'],
      dtype='object')